### PR TITLE
Prevent StackOverflowException when evaluating fragment as HTML attributes

### LINKED ISSUE #200: Processing knotx:snippet with a long attribute throws StackOverflowException
**Processing knotx:snippet with a long attribute throws StackOverflowException**
A clear and concise description of what the bug is. Make sure to include a version o Knot.x you use.
providing a <knotx:snippet that contains a long attribute causes StackOverflowException within regex processing in https://github.com/Knotx/knotx-fragments/blob/master/supplier/html-splitter/src/main/java/io/knotx/fragments/supplier/html/splitter/HtmlAttributesParser.java

**To Reproduce**
Create a knotx:snippet with a long-enough configuration attribute - in our case it was: 1571 chars

**Expected behavior**
No matter how long the knotx:snippet tag and it's configuration, everything should work correctly without exceptions.
possible solution: The regular expression in HtmlAttributesParser.java should probably be rewritten to a more effective handling way. maybe use jsoup?

**Additional context**
case which throws exception for us:
<knotx:snippet data-knotx-task="call-stocks-sedol-api" indices-configuration="eyJGVFNFIDEwMCI6eyJpZCI6IlVLWCIsIm5hbWUiOiJGVFNFIDEwMCIsImluZGV4UGF0aCI6Imh0dHBzOi8vd3d3LmhsLmNvLnVrL3NoYXJlcy9zdG9jay1tYXJrZXQtc3VtbWFyeS9mdHNlLTEwMCJ9LCJGVFNFIDI1MCI6eyJpZCI6Ik5NWCIsIm5hbWUiOiJGVFNFIDI1MCIsImluZGV4UGF0aCI6Imh0dHBzOi8vd3d3LmhsLmNvLnVrL3NoYXJlcy9zdG9jay1tYXJrZXQtc3VtbWFyeS9mdHNlLTI1MCJ9LCJGVFNFIEFsbCBTaGFyZSI6eyJpZCI6IkFTWCIsIm5hbWUiOiJGVFNFIEFsbCBTaGFyZSIsImluZGV4UGF0aCI6Imh0dHBzOi8vd3d3LmhsLmNvLnVrL3NoYXJlcy9zdG9jay1tYXJrZXQtc3VtbWFyeS9mdHNlLWFsbC1zaGFyZSJ9LCJGVFNFIHRlY2hNQVJLIDEwMCI6eyJpZCI6IlQxWCIsIm5hbWUiOiJGVFNFIHRlY2hNQVJLIDEwMCIsImluZGV4UGF0aCI6Imh0dHBzOi8vd3d3LmhsLmNvLnVrL3NoYXJlcy9zdG9jay1tYXJrZXQtc3VtbWFyeS9mdHNlLXRlY2htYXJrLTEwMCJ9LCJGVFNFIHNtYWxsIGNhcCI6eyJpZCI6IlNNWCIsIm5hbWUiOiJGVFNFIHNtYWxsIGNhcCIsImluZGV4UGF0aCI6Imh0dHBzOi8vd3d3LmhsLmNvLnVrL3NoYXJlcy9zdG9jay1tYXJrZXQtc3VtbWFyeS9mdHNlLXNtYWxsLWNhcCJ9LCJGVFNFIEFJTSAxMDAiOnsiaWQiOiJBSU0xIiwibmFtZSI6IkZUU0UgQUlNIDEwMCIsImluZGV4UGF0aCI6Imh0dHBzOi8vd3d3LmhsLmNvLnVrL3NoYXJlcy9zdG9jay1tYXJrZXQtc3VtbWFyeS9mdHNlLWFpbS0xMDAifSwiTkFTREFRIjp7ImlkIjoiQ09NUCIsIm5hbWUiOiJOQVNEQVEiLCJpbmRleFBhdGgiOiJodHRwczovL3d3dy5obC5jby51ay9zaGFyZXMvc3RvY2stbWFya2V0LXN1bW1hcnkvbmFzZGFxIn0sIlhldHJhIERBWCI6eyJpZCI6IkRBWCIsIm5hbWUiOiJYZXRyYSBEQVgiLCJpbmRleFBhdGgiOiJodHRwczovL3d3dy5obC5jby51ay9zaGFyZXMvc3RvY2stbWFya2V0LXN1bW1hcnkveGV0cmEtZGF4In0sIkNBQyA0MCI6eyJpZCI6IkNBQyIsIm5hbWUiOiJDQUMgNDAiLCJpbmRleFBhdGgiOiJodHRwczovL3d3dy5obC5jby51ay9zaGFyZXMvc3RvY2stbWFya2V0LXN1bW1hcnkvY2FjLTQwIn0sIklCRVggMzUiOnsiaWQiOiJJQkVYIiwibmFtZSI6IklCRVggMzUifSwiRlRTRSBNSUIiOnsiaWQiOiJNSUIiLCJuYW1lIjoiRlRTRSBNSUIifX0=">

### PR DESCRIPTION
**Pull request by marcinus**
## Description
This PR changes the Regular Expression in `HtmlAttributesParser` to reduce the likelihood of encountering `StackOverflowException`.
The regex of form `'(\\'|[^'])*'` in `HtmlAttributesParser` created a huge amount of branching, resulting in `StackOverflowExpression`.
The changed regexp form `'(\\.|[^\\']*)*'` does not yield such a huge branching and was tested to successfully handle large objects (tested with up to 146MB input with Json, base64 and mixed values).

## Motivation and Context
Fixes #200 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/Knotx/knotx/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

---
I hereby agree to the terms of the Knot.x Contributor License Agreement.

### CODE REVIEW

File: supplier/html-splitter/src/test/java/io/knotx/fragments/supplier/html/splitter/HtmlAttributesParserTest.java [hunk 1]
```diff
@@ -18,15 +18,32 @@
...
 class HtmlAttributesParserTest {
 
+  private static final String SOME_KEY = "some-parameter";
+
+  private static final String SINGLE_QUOTES_ESCAPED = "\\' Some text \\'having\\' single quotes escaped \\'\\' and some \"double quotes\" \\'";
+  private static final String DOUBLE_QUOTES_ESCAPED = "\\\" Some text \\\"having\\\" double quotes escaped '' and some 'single quotes' \\\"";
+
   private HtmlAttributesParser tested;
 
+  private static String json;
```
Comment (Skejven) [inline supplier/html-splitter/src/test/java/io/knotx/fragments/supplier/html/splitter/HtmlAttributesParserTest.java:38]: `json` and `bas64` don't have to be static.

**Review by Skejven — APPROVED** [review]

File: supplier/html-splitter/src/test/java/io/knotx/fragments/supplier/html/splitter/HtmlAttributesParserTest.java (hunk 1 above)
Comment (marcinus) [reply supplier/html-splitter/src/test/java/io/knotx/fragments/supplier/html/splitter/HtmlAttributesParserTest.java]: Done

**Review by tomaszmichalak — APPROVED** [review]
